### ISSUE TITLE
action GetAddonInfos under service WANCommonIFC:1

### ISSUE THREAD

**Issue by wfjm** [yunity/fritzinfluxdb#5] opened 2020-06-11 16:13 UTC
I use a Fritz!Box 7590 with Fritz!OS: 07.12 (lastest)

`fritzinfluxdb` aborts when started with `default.ini`. The culprit is that the action `GetAddonInfos` used in clause `[service1]` of the ini file is not available in service `WANCommonInterfaceConfig`.

It turns out that this action is available for service `WANCommonIFC:1`, as all other actions used by clause `[service1]`. See appended lists. 

So just changing the service name from `WANCommonInterfaceConfig:1` to `WANCommonIFC:1` was sufficient to make it work in my case.

Did this change in recent Fritz!OS versions ? Or is this action provided by different services depending on Fritz!Box model ? In the first case _default.ini_ should be updated, in the second case it's helpful to give some hints in the README.

---
output from `fritzconnection -c -u <user> -p <pwd>`
```
Servicename:        WANCommonIFC:1
Actionname:         GetAddonInfos
                        ('NewAutoDisconnectTime', 'out', 'ui4')
                        ('NewByteReceiveRate', 'out', 'ui4')
                        ('NewByteSendRate', 'out', 'ui4')
                        ('NewDNSServer1', 'out', 'string')
                        ('NewDNSServer2', 'out', 'string')
                        ('NewIdleDisconnectTime', 'out', 'ui4')
                        ('NewPacketReceiveRate', 'out', 'ui4')
                        ('NewPacketSendRate', 'out', 'ui4')
                        ('NewRoutedBridgedModeBoth', 'out', 'ui1')
                        ('NewTotalBytesReceived', 'out', 'ui4')
                        ('NewTotalBytesSent', 'out', 'ui4')
                        ('NewUpnpControlEnabled', 'out', 'boolean')
                        ('NewVoipDNSServer1', 'out', 'string')
                        ('NewVoipDNSServer2', 'out', 'string')
                        ('NewX_AVM_DE_TotalBytesReceived64', 'out', 'string')
                        ('NewX_AVM_DE_TotalBytesSent64', 'out', 'string')
                        ('NewX_AVM_DE_WANAccessType', 'out', 'string')
Actionname:         GetCommonLinkProperties
                        ('NewLayer1DownstreamMaxBitRate', 'out', 'ui4')
                        ('NewLayer1UpstreamMaxBitRate', 'out', 'ui4')
                        ('NewPhysicalLinkStatus', 'out', 'string')
                        ('NewWANAccessType', 'out', 'string')
Actionname:         GetTotalBytesReceived
                        ('NewTotalBytesReceived', 'out', 'ui4')
Actionname:         GetTotalBytesSent
                        ('NewTotalBytesSent', 'out', 'ui4')
Actionname:         GetTotalPacketsReceived
                        ('NewTotalPacketsReceived', 'out', 'ui4')
Actionname:         GetTotalPacketsSent
                        ('NewTotalPacketsSent', 'out', 'ui4')
Actionname:         X_AVM_DE_GetDsliteStatus
                        ('NewX_AVM_DE_DsliteStatus', 'out', 'boolean')
Actionname:         X_AVM_DE_GetIPTVInfos
                        ('NewX_AVM_DE_IPTV_Enabled', 'out', 'boolean')
                        ('NewX_AVM_DE_IPTV_Provider', 'out', 'string')
                        ('NewX_AVM_DE_IPTV_URL', 'out', 'string')

Servicename:        WANCommonInterfaceConfig:1
Actionname:         GetCommonLinkProperties
                        ('NewLayer1DownstreamMaxBitRate', 'out', 'ui4')
                        ('NewLayer1UpstreamMaxBitRate', 'out', 'ui4')
                        ('NewPhysicalLinkStatus', 'out', 'string')
                        ('NewWANAccessType', 'out', 'string')
Actionname:         GetTotalBytesReceived
                        ('NewTotalBytesReceived', 'out', 'ui4')
Actionname:         GetTotalBytesSent
                        ('NewTotalBytesSent', 'out', 'ui4')
Actionname:         GetTotalPacketsReceived
                        ('NewTotalPacketsReceived', 'out', 'ui4')
Actionname:         GetTotalPacketsSent
                        ('NewTotalPacketsSent', 'out', 'ui4')
Actionname:         X_AVM-DE_GetOnlineMonitor
                        ('NewSyncGroupIndex', 'in', 'ui4')
                        ('NewSyncGroupMode', 'out', 'string')
                        ('NewSyncGroupName', 'out', 'string')
                        ('NewTotalNumberSyncGroups', 'out', 'ui4')
                        ('Newds_current_bps', 'out', 'string')
                        ('Newmax_ds', 'out', 'ui4')
                        ('Newmax_us', 'out', 'ui4')
                        ('Newmc_current_bps', 'out', 'string')
                        ('Newprio_default_bps', 'out', 'string')
                        ('Newprio_high_bps', 'out', 'string')
                        ('Newprio_low_bps', 'out', 'string')
                        ('Newprio_realtime_bps', 'out', 'string')
                        ('Newus_current_bps', 'out', 'string')
Actionname:         X_AVM-DE_SetWANAccessType
                        ('NewAccessType', 'in', 'string')
```

**Comment by bb-Ricardo** [comment] 2020-07-28 20:44
Hi,

I found the issue. The problem is the fritzconnection library version. It works until version 0.7.3.

Will have a look into adopting newer library versions.

**Comment by bb-Ricardo** [comment] 2020-07-30 22:13
this should be fixed in branch "next-release"

could you test this please

**Comment by bb-Ricardo** [comment] 2020-08-03 08:56
released new version

**Closed by bb-Ricardo** 2020-08-03 08:56 UTC
